[package]
name = "titan_control"
version = "1.0.0"
edition = "2024"

[dependencies]
gtk4 = "0.11"
libadwaita = "0.9.1"
async-channel = "2.5.0"
ksni = { version = "0.3", features = ["blocking"] }
image = "0.25.9"
i2c-linux = "0.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
